name: Build
on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: Environment to deploy
        required: true
      

jobs:   
  install-and-build:
    name: NPM install and build site
    environment: ${{ inputs.environment }}
    runs-on: [ ubuntu-latest-16-core-64gb, ubuntu-latest ]
    defaults:
      run:
        shell: bash
        working-directory: site/gatsby-site
    steps:

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }} # This is dangerous without the first access check

      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v3.0.5
        env:
          cache-name: cache-install-folder
        with:
          path: |
            site/gatsby-site/node_modules
            ~/.cache/Cypress
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install NPM dependencies
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        uses: cypress-io/github-action@v4
        with:
          working-directory: site/gatsby-site
          # just perform install
          runTests: false
          install-command: npm ci

      - name: Delete netlify.toml
        run: rm -f netlify.toml
  
      - name: Rename github-netlify.toml to netlify.toml
        run: mv github-netlify.toml netlify.toml

      - name: Install Netlify CLI
        run: npm install netlify-cli -g

      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        
      - name: Build using Netlify
        run: netlify build --context deploy-preview
        working-directory: site/gatsby-site
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          E2E_ADMIN_USERNAME: ${{ secrets.E2E_ADMIN_USERNAME }}
          E2E_ADMIN_PASSWORD: ${{ secrets.E2E_ADMIN_PASSWORD }}
          ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}
          GATSBY_ALGOLIA_APP_ID: ${{ secrets.GATSBY_ALGOLIA_APP_ID }}
          GATSBY_ALGOLIA_SEARCH_KEY: ${{ secrets.GATSBY_ALGOLIA_SEARCH_KEY }}
          GATSBY_AVAILABLE_LANGUAGES: ${{ secrets.GATSBY_AVAILABLE_LANGUAGES }}
          GATSBY_REALM_APP_ID: ${{ secrets.GATSBY_REALM_APP_ID }}
          GOOGLE_TRANSLATE_API_KEY: ${{ secrets.GOOGLE_TRANSLATE_API_KEY }}
          MONGODB_CONNECTION_STRING: ${{ secrets.MONGODB_CONNECTION_STRING }}
          MONGODB_REPLICA_SET: ${{ secrets.MONGODB_REPLICA_SET }}
          MONGODB_TRANSLATIONS_CONNECTION_STRING: ${{ secrets.MONGODB_TRANSLATIONS_CONNECTION_STRING }}
          MONGODB_MIGRATIONS_CONNECTION_STRING: ${{ secrets.MONGODB_MIGRATIONS_CONNECTION_STRING }}
          GATSBY_REALM_APP_GRAPHQL_URL: ${{ secrets.GATSBY_REALM_APP_GRAPHQL_URL }}
          GATSBY_PRISMIC_REPO_NAME: ${{ secrets.GATSBY_PRISMIC_REPO_NAME }}
          PRISMIC_ACCESS_TOKEN: ${{ secrets.PRISMIC_ACCESS_TOKEN }}
          NODE_OPTIONS: --dns-result-order=ipv4first
          GATSBY_ROLLBAR_TOKEN: ${{ secrets.GATSBY_ROLLBAR_TOKEN }} 

      - name: Cache public folder
        uses: actions/cache@v3.0.5
        env:
          cache-name: cache-public
        with:
          path: |
            site/gatsby-site
            .git
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ github.event.pull_request.head.sha }}
