name: Deploy to Netlify
on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
jobs:
  netlify-deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      pull-requests: write
    steps:
      - name: Cache public folder
        uses: actions/cache@v3.0.5
        env:
          cache-name: cache-public
        with:
          path: |
            site/gatsby-site
            .git
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ github.event.pull_request.head.sha }}

      - name: Install Netlify CLI
        run: npm install netlify-cli -g

      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

      - name: Upload to netlify
        id: deploy-netlify
        working-directory: site/gatsby-site
        run: |
          DEPLOY_OUTPUT=$(netlify deploy --json --alias=pr-${{ github.event.pull_request.number }})
          echo "::set-output name=deploy_log::$DEPLOY_OUTPUT"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
  
      - name: Comment on PR
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const deployOutput = `${{ steps.deploy-netlify.outputs.deploy_log }}`;
            const deployData = JSON.parse(deployOutput);
            const comment = `🚀 Deployed to Netlify!\n\n✅ Build Log: \n${deployData.log}\n\n🔗 Preview URL: ${deployData.deploy_url}`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
