name: Deploy to Netlify
on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
jobs:   

  netlify-deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions: 
      pull-requests: write
    steps:

      - name: Cache public folder
        uses: actions/cache@v3.0.5
        env:
          cache-name: cache-public
        with:
          path: |
            site/gatsby-site/public
            site/gatsby-site/.netlify
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ github.event.pull_request.head.sha }}

      - name: Upload to netlify
        uses: netlify/actions/cli@master
        id: deploy-netlify
        with:
          args: deploy --dir=site/gatsby-site/public --functions=site/gatsby-site/src/api --alias=pr-${{ github.event.pull_request.number }}

        env:
            NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
            NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

      - name: Netlify Preview URL 
        uses: unsplash/comment-on-pr@v1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OUTPUT: "This pull request is being automatically deployed to Netlify.\n\n🔍 Inspect: ${{ steps.deploy-netlify.outputs.NETLIFY_LOGS_URL }}\n✅ Preview: ${{ steps.deploy-netlify.outputs.NETLIFY_URL }}"
        with:
          msg: ${{ env.OUTPUT }}
          check_for_duplicate_msg: false
