name: Deploy Preview Branch

on:
  pull_request:
    branches: 
      - staging
  pull_request_target:
    branches:
      - staging
    types: [opened, synchronize, reopened]
jobs:
  call-build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      environment: staging

  call-test:
    uses: ./.github/workflows/test.yml
    needs: call-build
    secrets: inherit
    with:
      environment: staging

  call-deploy:
    uses: ./.github/workflows/deploy.yml
    needs: call-build
    secrets: inherit
    permissions: 
      pull-requests: write
    with:
      environment: staging