name: Deploy
on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true

jobs:
  test:
    name: Run Cypress tests
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: site/gatsby-site
    strategy:
      # when one test fails, DO NOT cancel the other
      # containers, because this will kill Cypress processes
      # leaving the Dashboard hanging ...
      # https://github.com/cypress-io/github-action/issues/48
      fail-fast: false
      matrix:
        # run 10 copies of the current job in parallel
        containers: [1, 2, 3, 4]
    # stop the job if it runs over 20 minutes
    # to prevent a hanging process from using all your CI minutes
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: 
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Read node modules from cache
        id: cache-nodemodules-2
        uses: actions/cache/restore@v3
        env:
          cache-name: cache-install-folder
        with:
          path: |
            site/gatsby-site/node_modules
            ~/.cache/Cypress
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install NPM dependencies
        if: steps.cache-nodemodules-2.outputs.cache-hit != 'true'
        uses: cypress-io/github-action@v4
        with:
          working-directory: site/gatsby-site
          # just perform install
          runTests: false
          install-command: npm ci --legacy-peer-deps

      - name: Read Artifacts from cache
        uses: actions/cache/restore@v3
        env:
          cache-name: cache-artifacts
        with:
          path: |
            site/gatsby-site/public
            site/gatsby-site/.netlify/functions
            site/gatsby-site/.netlify/functions-internal
            .git
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ github.event.pull_request.head.sha }}
          fail-on-cache-miss: true

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: site/gatsby-site
          install: false
          config-file: cypress.config.js
          record: true
          parallel: true
          group: "Cypress e2e tests"
          tag: ${{ steps.extract_branch.outputs.branch }}
          start: node node_modules/.bin/gatsby serve -p 8000 -H 127.0.0.1
          wait-on: http://127.0.0.1:8000
          wait-on-timeout: 60
        env:
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          E2E_ADMIN_USERNAME: ${{ secrets.E2E_ADMIN_USERNAME }}
          E2E_ADMIN_PASSWORD: ${{ secrets.E2E_ADMIN_PASSWORD }}
          ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}
          GATSBY_ALGOLIA_APP_ID: ${{ secrets.GATSBY_ALGOLIA_APP_ID }}
          GATSBY_ALGOLIA_SEARCH_KEY: ${{ secrets.GATSBY_ALGOLIA_SEARCH_KEY }}
          GATSBY_AVAILABLE_LANGUAGES: ${{ secrets.GATSBY_AVAILABLE_LANGUAGES }}
          GATSBY_REALM_APP_ID: ${{ secrets.GATSBY_REALM_APP_ID }}
          GOOGLE_TRANSLATE_API_KEY: ${{ secrets.GOOGLE_TRANSLATE_API_KEY }}
          MONGODB_CONNECTION_STRING: ${{ secrets.MONGODB_CONNECTION_STRING }}
          MONGODB_REPLICA_SET: ${{ secrets.MONGODB_REPLICA_SET }}
          MONGODB_TRANSLATIONS_CONNECTION_STRING: ${{ secrets.MONGODB_TRANSLATIONS_CONNECTION_STRING }}
          MONGODB_MIGRATIONS_CONNECTION_STRING: ${{ secrets.MONGODB_MIGRATIONS_CONNECTION_STRING }}
          GATSBY_REALM_APP_GRAPHQL_URL: ${{ secrets.GATSBY_REALM_APP_GRAPHQL_URL }}
          GATSBY_ROLLBAR_TOKEN: ${{ secrets.GATSBY_ROLLBAR_TOKEN }}
          # Since this is triggered on a pull request, we set the commit message to the pull request title
          COMMIT_INFO_MESSAGE: ${{ github.event.pull_request.title }}
